### ISSUE TITLE
All sorts of compiler errors when enabling SIMD with FFTW

### ISSUE THREAD

**Issue by ghost** [xtensor-stack/xtensor-fftw#61] opened 2022-02-23 14:32 UTC
adding #define XTENSOR_USE_XSIMD results in the errors below:

<img width="1457" alt="image" src="https://user-images.githubusercontent.com/35534426/155339670-9899d972-a17a-4c0d-b4ba-0ae527919946.png">

Configuration:
C++20
VS2019
Xtensor 0.24.0
Xsimd 8.0.3

**Comment by egpbos** [comment] 2022-06-07 08:25
@dahubley does this only happen when FFTW is thrown in the mix? Can you isolate the code you are compiling that specifically triggers the failures?

@JohanMabille any immediate clues?

**Comment by spectre-ns** [comment] 2023-02-27 13:29
@egpbos  see attached logs.
[Logs.txt](https://github.com/xtensor-stack/xtensor-fftw/files/10840062/Logs.txt)

Lots of redefinition errors.

**Comment by egpbos** [comment] 2023-06-08 12:55
Sorry for the slow response. Just quickly looking at the logs, I don't see anything that immediately makes clear to me where to look further. It does look like this is not a particularly "minimum failing example". It could be very helpful if you set up a very compact compilation unit, ideally just a main function with a single call that fails. Then perhaps someone can help you debug, otherwise we don't have anything to go by.

**Comment by spectre-ns** [comment] 2023-06-08 12:59
> Sorry for the slow response. Just quickly looking at the logs, I don't see anything that immediately makes clear to me where to look further. It does look like this is not a particularly "minimum failing example". It could be very helpful if you set up a very compact compilation unit, ideally just a main function with a single call that fails. Then perhaps someone can help you debug, otherwise we don't have anything to go by.

I will add it in 5 minutes.

**Comment by spectre-ns** [comment] 2023-06-08 13:08
I cannot reproduce closing.

**Comment by egpbos** [comment] 2023-06-08 13:14
Thanks for the quick follow-up, closing :) Feel free to reopen or open a new issue if you are able to reproduce later.

**Closed by egpbos** 2023-06-08 13:14 UTC
